Feature/86cwjx80t error modal gemini
Monash-FIT3170/Keep-Me-Posted pull request #160
Opened 2024-10-01 12:46 UTC by AlexesGitHub

https://app.clickup.com/t/86cwjx80t

2024-10-02 17:18 UTC, bdan0005 requested changes
Can you add a more appropriate message for the general Gemini error, and remove the extra comma in the header?

2024-10-07 01:15 UTC, harry-lane-monash approved these changes

2024-10-07 05:34 UTC, harry-lane-monash approved these changes

2024-10-07 05:53 UTC, bdan0005 approved these changes

2024-10-07 07:25 UTC, merged