Rendering different title and subtitle on page depending on whether the summary and subject has been generated and is in the svelte store
Monash-FIT3170/Keep-Me-Posted pull request #81
Opened 2024-08-12 05:13 UTC by dyarmsh

2024-08-12 05:15 UTC, bdan0005 approved these changes

2024-08-12 05:16 UTC, dnylng commented
looks good to me

2024-08-13 14:16 UTC, aleu0007 requested changes

2024-08-13 14:16 UTC, aleu0007 commented on frontend/src/routes/generate_summary/+page.svelte
>      <div class="text-4xl font-inter font-bold mb-4 text-black flex flex-col justify-center items-center mt-20">
Please change to use h1/h2/h3/subheading tag. Remove redundant styling. refer to app.css for what has already been applied

2024-08-13 14:16 UTC, aleu0007 commented on frontend/src/routes/generate_summary/+page.svelte
>      <div class="text-xl font-inter font-thin text-black flex flex-col justify-center items-center mt-6">
Same as above

2024-08-18 03:47 UTC, aleu0007 approved these changes

2024-08-18 03:49 UTC, aleu0007 approved these changes

2024-08-18 03:49 UTC, merged