Feature/86cw1rnwy + 86cw1rnyr error popups
Monash-FIT3170/Keep-Me-Posted pull request #97
Opened 2024-08-17 04:14 UTC by dnylng

the error popups for the following two scenarios

1. the file is over 120 minutes long

2. the file is not a mp3 or wav

for the 2nd error to to work there needs to be other files that can be accepted which is counterintuitive but still works it will have the error popup if you put in other files

2024-08-17 05:46 UTC, benjicherian requested changes
Hi Danny, love the work on the error pop-ups, on review, the first popup works as intended. However, the second one will never show due to the audio box's logic. Try refactoring this using the existing dropzone documentation.

https://www.npmjs.com/package/svelte-file-dropzone.

2024-08-17 06:18 UTC, bdan0005 requested changes
- Remove redundant error icon, it's already built into the pop up modal component. 
- You don't have to define a bool (showError) for showing the error, there is a public function inside the pop up modal component for doing so (togglePopUp()).

2024-08-17 13:48 UTC, bdan0005 approved these changes

2024-08-18 04:33 UTC, benjicherian approved these changes

2024-08-18 04:33 UTC, merged